### ISSUE TITLE
The app does not launch

### ISSUE THREAD

**Issue by RmK9** [veeenu/darksoulsiii-practice-tool#1]
Hey, was trying to test out the Practise tool for DS3, running on 1.04v patch. However nothing ever opens when you try to open the practise tool, there's no window, no errors, no logs (in event viewer or tool's folder), nothing. Tested in a clean Win10 VM running on 1903 build (mine's 1904) and it's the same. I had an old 0.5v in the speedsouls practise pack, that one opens a window and shows logs in the UI window, but doesn't support 1.04v unfortunately.

Does this tool still supposed to work? I'd provide any logs or any additional information, but there's nothing to work with, it's just that nothing happens when opening the app.

**Comment by veeenu** [comment]
Hi! Yes, the tool's supposed to work, but it does open no external window as the UI is now an in-game overlay. Do you first start DSIII and, afterwards, the tool?

As per the logging -- you are right and it would be beneficial. The tool is not updated often but I intend to provide long-term maintenance, so logging for debugging purposes is definitely something that's on the table for the future.

**Comment by RmK9** [comment]
Hi Andrea! Thank you for the quick response and all your hard work on this!

Thanks for explaining the external window and yeah I've tried all combinations now just in case, start DSIII while it's in the menu then start the tool or start DSIII while it's in the game and then start the tool - nothing happens when pressing F11 or any other of the hotkeys specified in the config.

Using latest build v1.0.2, no AV present, Windows Defender not complaining, but I've explicitly allowed that folder and app just in case, ran as admin, ran in compatibility mode.

Is there any process that starts with the app at all? I would love to provide any relevant information on this, but not sure what's needed.

The only information I can assume is that maybe some of my dependencies could be of different version (if the app relies on local ones at all), such as Python 2.7.15, but afaik Python was only used to compile the build, don't have any C++ related dev things installed.

Thanks for all the help!

**Comment by veeenu** [comment]
The debug build has some crude form of logging implemented, but that's stripped in the release build. I'm afraid I'll have to implement some file-based logging for it to be useful at all to debug crashes! I'll work on it asap, I anticipate it could be ready by next week if you want to check back.

>Is there any process that starts with the app at all? I would love to provide any relevant information on this, but not sure what's needed.

No, unfortunately the app must start after the game at all times because it works via DLL injection and a process needs to exist already to be found.

Thank you for your feedback and help so far! It'd be great if we could spot some bug I'm not aware of.

**Comment by RmK9** [comment]
Got it, thank you for your quick support with all of this.

I'll be travelling next week, but would love to test it out as soon as it's available!

Wish I could provide any more relevant information.

**Comment by veeenu** [comment]
Fixed the issue and released the updated version, with logging implemented as well.
The culprit was the injector not having enough space for enumerating all the processes and possibly some glitch in the case-insensitive string comparison function. Patched the first and yanked the second in favor of simple `std::string` equality.

https://github.com/veeenu/darksoulsiii-practice-tool/releases/tag/v1.0.3
