### ISSUE TITLE
Tool crashes on start

### ISSUE THREAD

**Issue by stas1c** [veeenu/darksoulsiii-practice-tool#21]
Tool just crashes on start. Tried to run tool and game as administrator - didn't helped.

[jdsd_dsiii_practice_tool.log](https://github.com/veeenu/darksoulsiii-practice-tool/files/11198985/jdsd_dsiii_practice_tool.log)

**Comment by veeenu** [comment]
Hi! It looks like there is an antivirus software running, or possibly other third party overlay software like RTSS.

**Comment by stas1c** [comment]
Hmm.. tried disabling antivirus and overlay from Amd Adrenaline software.. no luck. no idea what else could it be. But thanks for the answer.

**Comment by veeenu** [comment]
Can you provide other info about your system?
- Which operating system/CPU/GPU do you have?
- Where did you source your copy of Dark Souls III?
- Do you have other mods installed?

**Comment by veeenu** [comment]
> - GOTY edition from torrents

Oh, then this is expected. Pirated copies have modified .exe files and aren't ever going to be supported, for a few fundamental reasons:
- I can't reasonably track all modified exe files out there
- I don't want to execute modified code on my machine due to concerns about security
- I don't want to support piracy

You could try to run [codegen](https://github.com/veeenu/darksoulsiii-practice-tool#code-generation) and compile it yourself, but I won't be able to offer help in that regard. Besides, Dark Souls III can be found on sale at [reasonable prices](https://isthereanydeal.com/game/darksoulsiii/info/) from time to time.

**Comment by stas1c** [comment]
Got it. Thanks for your answers!
