### ISSUE TITLE
Gesture spawning not working 

### ISSUE THREAD

**Issue by Babzzii** [veeenu/darksoulsiii-practice-tool#28]
I tried to spawn in gestures but I can't use them, I get them in my inventory but not in gesture bar

**Comment by veeenu** [comment]
That's not really supported atm. The item list is autogenerated and contains (for some reason) gestures, but I believe the way of actually activating them to be something completely different from spawning an item.

I am not aware of what it takes to activate gestures. If there is interest and someone is able to contribute the feature I will add it, but otherwise it's going to be low priority unless there is a speedrun related use case for it.
